
server:
  port: 8000

spring:
  #数据源配置
  data:
    mongodb:
      # 主机地址
      #      host: 121.41.45.228
      # 数据库
      database: game

      username: root
      password: '123456'
      authentication-database: admin
      host: 192.168.10.62
      # 默认端口是27017
      port: 27017

  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379

  devtools:
    restart:
      #热部署默认会重启
      enabled: true
      #添加那个目录的文件需要restart
      additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: static/**,public/**




myconfig:
  #游戏请求地址
  game:
    ipPort: "192.168.10.62:9998"

  #日志配置
#logging:
#  level:
#    root: INFO
#  console:
#    level: INFO
#  file:
#    level: INFO
#    name: admin.log
#    path: ../logs
#    enabled: true