
server:
  port: 8000

spring:
  config:
    activate:
      on-profile:
        - prod
  #数据源配置
  data:
    mongodb:
      # 主机地址
      #      host: 121.41.45.228
      # 数据库
      database: manage
      username: root
      password: 'dd9876543210'
      authentication-database: admin
      host: 47.103.29.33
      # 默认端口是27017
      port: 27017

  redis:
    host: 47.103.29.33
    port: 6379
    username: root
    password: dd9876543210

  devtools:
    restart:
      #热部署默认会重启
      enabled: true
      #添加那个目录的文件需要restart
      additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: static/**,public/**
  jackson:
    time-zone: GMT+8




myconfig:
  #游戏请求地址
  game:
    ipPort: "47.103.89.32:9998"

  #日志配置
#logging:
#  level:
#    root: INFO
#  console:
#    level: INFO
#  file:
#    level: INFO
#    name: admin.log
#    path: ../logs
#    enabled: true